### ISSUE TITLE
FIT badge

### ISSUE THREAD

**Issue by k-doering-NOAA** [noaa-fisheries-integrated-toolbox/toolbox_web_templating#59]
@MargaretSiple-NOAA suggested a FIT Badge:

```
Is there already a badge that people can put in their GitHub repo READMEs to signal that the tool
 is in the FIT? It may seem redundant but it might really help raise awareness and use of the FIT

```

**Comment by k-doering-NOAA** [comment]
Megsie: An easy way to do this in the meantime might be to ask developers to add 'noaa-fit' or similar to the keywords in their repo. Takes just a second, makes it easier to search, etc

**Comment by k-doering-NOAA** [comment]
Example:
![My badge](https://img.shields.io/badge/NOAA%20FIT-Listed-blue.svg)
Different words can be used. We could even come up with different levels as part as our quality scheme, for example
![Onboarded badge](https://img.shields.io/badge/NOAA%20FIT-onboarded-blue.svg)
![Code review badge](https://img.shields.io/badge/NOAA%20FIT-Code%20Reviewed-green.svg)
![Operational badge](https://img.shields.io/badge/NOAA%20FIT-operational-blueviolet.svg)

**Comment by MargaretSiple-NOAA** [comment]
I love this! Are those standard colors, like the ones they use for R packages?  The badge is great.

**Comment by k-doering-NOAA** [comment]
Yep, there's a section on https://shields.io/ where you can see the colors available (or at least the standard ones; it might be possible to customize more). 

![the standard colors as on shields.io](https://user-images.githubusercontent.com/48930335/230785458-70dca93d-e863-4ecf-9a41-fd9153a3a708.png)

I think this can be part of our May FIT committee meeting on quality indicators/badging.

**Comment by k-doering-NOAA** [comment]
We are working on this in developing [tool quality schemes](https://docs.google.com/document/d/1-9qh3L_Ws6nN67R-oLpU_KDjP-7norn8Mhv1jnKjB9c/edit?usp=sharing)

**Comment by k-doering-NOAA** [comment]
closing this, since it will be addressed under the tool quality standards.
