### ISSUE TITLE
Fix logos and font size on filter menu

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [noaa-fisheries-integrated-toolbox/toolbox_web_templating#63]
On the filter menu on the github-dev site, the labels (Web app, executable, etc.) are different font sizes and the icons have some extra white space on the right side.

**Comment by k-doering-NOAA** [comment]
Thanks @ChristineStawitz-NOAA ! I think I need to modify the CSS file.

Here is a screenshot of the issue: 
![screenshot of font sizes and icons issue](https://user-images.githubusercontent.com/48930335/223501297-26ccefcb-fae5-4265-8ede-bc9ff5ea2744.png)

**Comment by k-doering-NOAA** [comment]
Thanks @ChristineStawitz-NOAA I was able to solve the different font sizes, but wasn't able to figure out the issue with extra whitespace, despite changing the css. Maybe I need to look at the original css to help me figure it out?

One work around we could do is to save all the icons with a white background, and turn off the white background and border. I might resort to this if I remain at a loss after looking at the original css file on main!

**Comment by k-doering-NOAA** [comment]
Fixed by using the workaround.
