### ISSUE TITLE
change Legacy badge name

### ISSUE THREAD

**Issue by cmlegault** [noaa-fisheries-integrated-toolbox/toolbox_web_templating#64]
I suggest changing the name of the Legacy badge to something like "Not Supported" or "No Longer Supported" (perhaps "Abandoned" <grin?>) and changing the description of the badge to something like "This tool is no longer supported due to either lack of time from the developer or lack of resources to maintain the code."

Rationale: I fear the term Legacy would be a real hindrance to our lawyers the next time we are sued over Gulf of Maine cod, which uses ASAP, or another stock that uses a tool from the original NOAA Fisheries Toolbox. I certainly would not want to have to explain to a judge why we are using a Legacy model that is recommended to be updated to a replacement tool when the opposing lawyers bring this website to the judge's attention. This wording also contradicts the spirit of Bai's recent paper which states "When applied to simulated data, all 4 models produced reliable estimates of assessment quantities of interest..." Clearly, these "legacy" models work and are being used. Just because the Toolbox decided that maintaining Visual Basic code for a graphical user interface is not a good use of their time (a decision I agree with), we need to be careful that we are not throwing out the baby with the bathwater as some of these models are still used to provide stock status determinations and catch advice for management.

**Comment by k-doering-NOAA** [comment]
@cmlegault, thank you for pointing this out - @ChristineStawitz-NOAA just brought up this point, too, that legacy may not be the right term. Furthermore, the decision to mark a model as legacy was not well thought out, at this point.

I think this is a bigger discussion for the FIT committee about what to do with older NFT models, perhaps? What are your thoughts?

What do you think about for now removing the term "Legacy models" altogether until we discuss with the committee a scheme for designating different support levels?

**Comment by cmlegault** [comment]
@k-doering-NOAA I support removing the term "Legacy" altogether and having a group discussion about how to handle these older models. Thanks.

**Comment by k-doering-NOAA** [comment]
@cmlegault I just removed legacy as a filter and button, as well as the keyword from any model files on the fit-dev site. Please let me know if you notice any instances I missed!
